### PR TITLE
use conda all the way and remove defaults

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@mwidjaja1, ping

**Comment by mwidjaja1** [comment]
Sorry for forgetting, I need to test this on my ARM Mac still. I vaguely recall a few of those packages not working in this configuration on ARM

**Comment by mwidjaja1** [comment]
Sorry again for the late review, but I did give it a try today.

On ARM, I still need Pip for tensorflow_estimator -- there's no ARM Conda version ready for it.
```
  - pip:
    - tensorflow_estimator
```

Could you try moving tensorflow_estimator back to Pip and trying to install the env on Intel (I think you had Intel?) again? If that works could you make an update so I can re-review?

Thanks!

**Comment by isuruf** [comment]
Can you check now? Fixed a typo. Works on Intel

**Comment by mwidjaja1** [comment]
Seems good for me now too, thanks!

**Pull request merged**
